---
- name: Deploy and configure Grafana
  hosts: grafana
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - software-properties-common
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: true
        state: started

    - name: Configure Grafana default admin password
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: "^;admin_password = .*"
        line: "admin_password = YourSecurePassword"
        state: present

    - name: Restart Grafana to apply configuration changes
      systemd:
        name: grafana-server
        state: restarted
