---
- name: Configure data source services
  hosts: data_sources
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Enable and start Prometheus
      systemd:
        name: prometheus
        enabled: true
        state: started

    - name: Install Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Enable and start Node Exporter
      systemd:
        name: prometheus-node-exporter
        enabled: true
        state: started
