---
- name: Install NGINX and configure index.html
  hosts: azurevms
  become: true
  tasks:
    - name: Ensure apt-get lock is released
      block:
        - name: Check if another apt process is running
          shell: pgrep -a apt || true
          register: apt_process
          failed_when: false

        - name: Kill any apt or dpkg processes
          shell: |
            pkill -9 -f apt || true
            pkill -9 -f dpkg || true
            sleep 5
          when: apt_process.stdout != ""

        - name: Wait for dpkg lock to be released
          wait_for:
            path: /var/lib/dpkg/lock-frontend
            state: absent
            timeout: 30

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create index.html with VM details
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes
