---
- name: Install NGINX and configure index.html
  hosts: azurevms
  become: true
  tasks:
    - name: Kill conflicting apt processes
      shell: |
        killall -9 apt apt-get || true
        sleep 5  # Allow the lock to release

    - name: Create index.html with VM details
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes

