---
- name: Install NGINX and configure index.html
  hosts: azurevms
  become: true
  tasks:
    - name: Kill conflicting apt processes
      shell: |
        killall -9 apt apt-get || true
        sleep 5  # Allow the lock to release

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Create index.html file with custom content
      copy:
        dest: /var/www/html/index.html
        content: "Ansible the best for <h1>Hostname: $(hostname)</h1>"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: yes

